package com.darkframe.icons.engine.apply

/**
 * Samsung One UI capability model.
 *
 * One UI Home does not expose a public API for replacing other apps' icons. Theme Park can consume
 * an installed third-party icon pack and apply it in a batch, but it performs the import/save/apply
 * itself. Runtime bitmaps generated by DarkFrame cannot be injected into Theme Park through a
 * public API. Keeping that boundary here prevents the UI from promising a silent "Apply all".
 */
object SamsungThemeSupport {
    const val ONE_UI_HOME = "com.sec.android.app.launcher"
    const val THEME_PARK = "com.samsung.android.themedesigner"
    const val GOOD_LOCK = "com.samsung.app.goodlock"
    const val GOOD_LOCK_LEGACY = "com.samsung.android.goodlock"
    const val GALAXY_STORE = "com.sec.android.app.samsungapps"

    fun galaxyStoreUri(packageName: String): String = "samsungapps://ProductDetail/$packageName"
    fun playStoreUri(packageName: String): String = "market://details?id=$packageName"

    fun isOneUiHome(launcherPackage: String?): Boolean = launcherPackage == ONE_UI_HOME

    /**
     * Theme Park is the shortest legitimate route. Good Lock is detected for status/help, but when
     * Theme Park itself is missing we link to Theme Park directly instead of making the user walk
     * through Good Lock first.
     */
    fun stateFor(
        themeParkInstalled: Boolean,
        goodLockInstalled: Boolean,
        themeParkLaunchResolvable: Boolean,
        themeParkStoreResolvable: Boolean,
    ): SamsungCapabilityState = when {
        themeParkInstalled && themeParkLaunchResolvable ->
            SamsungCapabilityState.Ready(goodLockInstalled)
        !themeParkInstalled && themeParkStoreResolvable ->
            SamsungCapabilityState.NeedsThemePark(goodLockInstalled)
        else -> SamsungCapabilityState.Unavailable(goodLockInstalled)
    }
}

sealed interface SamsungCapabilityState {
    val goodLockInstalled: Boolean

    data class Ready(override val goodLockInstalled: Boolean) : SamsungCapabilityState
    data class NeedsThemePark(override val goodLockInstalled: Boolean) : SamsungCapabilityState
    data class Unavailable(override val goodLockInstalled: Boolean) : SamsungCapabilityState
}

enum class SamsungApplyStep {
    OPEN_THEME_PARK,
    INSTALL_THEME_PARK,
}
